version: "3.4"

networks:
  local-net:
    driver: bridge
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - PORT=${EXPRESS_PORT}
    user: node
    working_dir: /home/node/app
    env_file:
      - ./.env
    volumes:
      - ./src:/home/node/app/src
    ports:
      - ${EXPRESS_PORT}:${EXPRESS_PORT}
    depends_on:
      - db
    networks:
      - local-net
    command: "npm run start"

  db:
    image: mysql:5.7
    container_name: mysql_db
    networks:
      - local-net
    env_file:
      - ./.env
    restart: always
    environment:
      MYSQL_DATABASE: ${TYPEORM_DATABASE}
      MYSQL_USER: ${TYPEORM_USERNAME}
      MYSQL_ROOT_PASSWORD: ${TYPEORM_PASSWORD}
    ports:
      - ${EXPOSE_DATABASE}:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./db-dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql